manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: tri-state
      url-base: https://github.com/caksoylar
  projects:
    - name: zmk
      remote: tri-state
      revision: experimental
      import: app/west.yml
  self:
    path: config
